server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: https://auth-service-tzq7.onrender.com
          predicates:
            - Path=/auth/**

        - id: property-service
          uri: https://property-service-5n1v.onrender.com
          predicates:
            - Path=/properties/**

        - id: booking-service
          uri: https://booking-service-j42a.onrender.com
          predicates:
            - Path=/bookings/**

        - id: payment-route
          uri: https://booking-service-j42a.onrender.com
          predicates:
            - Path=/payments/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info

